name: hydrion
description: Hydrion.ai - AI-powered hydration companion. Secure, privacy-first, multi-language.
version: 1.0.0+1
publish_to: "none"
developer: "The 1807"

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  yaml: ^3.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/icon1807.png
    - config/
  generate: true

platforms:
  android:
  ios:
  web:
  macos:
  windows:
